version: "3"
services:
  nginx-plus:
    image: nginxplus
    build:
      context: .
      dockerfile: ./Dockerfile
      secrets: [nginx-crt, nginx-key]
    container_name: nginx-plus
    ports: ["443:443"]
    volumes:
      - $PWD/nginx.conf:/etc/nginx/nginx.conf
      - $PWD/conf.d:/etc/nginx/conf.d
      - $PWD/certs:/etc/nginx/certs
secrets:
  nginx-crt:
    file: ./nginx-repo.crt
  nginx-key:
    file: ./nginx-repo.key
