version: "3"
services:
  nginx-plus:
    image: nginxplus
    build:
      dockerfile: ./Dockerfile
      no_cache: true
      secrets: [nginx-crt, nginx-key]
    container_name: nginx-plus
    ports:
      - 443:443
    volumes:
      - $PWD/nginx.conf:/etc/nginx/nginx.conf
      - $PWD/certs:/etc/nginx/certs
secrets:
  nginx-crt:
    file: ./nginx-repo.crt
  nginx-key:
    file: ./nginx-repo.key
